name: dart_markdown
version: 3.1.0

description: A portable Markdown library written in Dart that can parse
  Markdown into AST and HTML.
repository: https://github.com/tagnote-app/dart_markdown

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  source_span: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.5
  build_version: ^2.0.3
  build_web_compilers: ^3.0.0
  collection: ^1.15.0
  html: ^0.15.0
  io: ^1.0.0
  js: ^0.6.3
  lints: ^2.0.0
  meta: ^1.3.0
  path: ^1.8.0
  test: ^1.16.0
  yaml: ^3.0.0
